language: python

python:
  - "3.6"
  - "3.7"

dist: xenial

sudo: false

services:
  - docker

before_install:
  - git clone https://github.com/oceanprotocol/docker-images
  - cd docker-images
  - bash -x start_ocean.sh --latest --no-brizo --no-pleuston --no-secret-store --local-spree-node 2>&1 > start_ocean.log &

install: pip install -U tox-travis

script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
  on:
    tags: true
    repo: oceanprotocol/squid-py
    python: 3.6
