language: python
matrix:
  include:
    - python: 3.6
      dist: xenial
      sudo: true

sudo: required
services:
- docker

before_install:
- docker-compose -f docker/docker-compose.yml up -d
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
  on:
    tags: true
    repo: oceanprotocol/squid-py
    python: 3.6
